### ISSUE TITLE
Integrate chess client with API

### ISSUE THREAD

**Issue by zacowan** [zacowan/chess-to-speech#28]
For more info on the API endpoints, see `/andy_api/api/api_routes.py`.

- [x] Wakeup phrase should start the game and generate a unique session ID
- [x] Make a request to an endpoint if a user talks (POST localhost:5000/api/get-response)
- [x] If a user performs a move, make a request to get Andy's move (GET localhost:5000/api/get-andy-move-response)
- [x] The client should update the board upon receiving a board string

**Comment by Legacy35** [comment]
tasks completed
