### ISSUE TITLE
Client improvements

### ISSUE THREAD

**Issue by zacowan** [zacowan/chess-to-speech#39]
- [x] Client should update the board when receiving a new board string
- [x] Client should get a new board string and audio response from a separate API endpoint when it is Andy's turn to make a move (work with Nate and see branch `feat/andy-move-response`)
- [x] Client should have a screen before a game has started ("Waiting to start game...")
- [x] The client should have an indicator showing that the microphone is on and accepting input
- [x] The client should never crash. It should display some text if an error has occurred and recover appropriately
- [x] The client should have a dedicated portion of the screen for showing what the user spoke as text and what the system responded with as text

**Comment by Legacy35** [comment]
all tasks completed
